spring.application.name=openai
server.port=8085

#For Open AI
#spring.ai.openai.api-key=sk-proj-xxx
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#For Ollama
#To tell spring ai that we use ollama
spring.ai.model.chat=ollama
#To tell spring ai about model which we are running using ollama
spring.ai.ollama.chat.options.model=gemma3:1b
